class ElizaChatData():
    def __init__(self):
        self.psychobabble = [

            [r'(\ssorry|\sapologize)',
            ["Please don't apologize.",
            "Apologies are not necessary.",
            "I've told you that apologies are not required.",
            "It did not bother me.  Please continue.",
            "I have no feelings. Do continue.",
            "There is nothing to worry about"]],

            [r'(.*)(remember$)',
            ["Do you often think of that ?",
            "Does thinking of that bring anything else to mind ?",
            "What else do you recollect ?",
            "Why do you remember that just now ?",
            "What in the present situation reminds you of that ?",
            "What is the connection between me and that ?",
            "What else do you remember about that?"]],

            [r'(.*)i remember (.*)',
            ["Do you often think of {1} ?",
            "Does thinking of {1} bring anything else to mind ?",
            "What else do you recollect ?",
            "Why do you remember {1} just now ?",
            "What in the present situation reminds you of {1} ?",
            "What is the connection between me and {1} ?",
            "What else do you remember about '{1}'?"]],

            [r'(.*)you remember(.*)',
            ["How could I forget {1} ?",
            "What about {1} should I remember ?",
            "Did you think I would forget {1} ?",
            "Why do you think I should recall {1} now ?",
            "What about {1} is interesting ?",
            "What about {1} ?",
            "You mentioned {1} ?"]],

            [r'(.*)(forget$)',
            ["Does forgetting bother you ?",
            "It could be a mental block ?",
            "Sometimes we are forgetful ?",
            "Why do you ask ?",
            "Ahhh... what was it again ?",
            "Are you sure that can be recalled ?"]],

            [r'(.*)i forget(.*)',
            ["Can you think of why you might forget {1} ?",
            "Why can't you remember {1} ?",
            "How often do you think of {1} ?",
            "Does it bother you to forget that ?",
            "Could it be a mental block ?",
            "Are you generally forgetful ?",
            "Do you think you are suppressing {1} ?"]],

            [r'(.*)you forget(\w+.*)',
            ["Why do you ask ?",
            "Are you sure you told me ?",
            "Would it bother you if I forgot {1} ?",
            "Why should I recall {1} just now ?",
            "Tell me more about {1}."]],

            [r'^if| if(\w+.*)',
            ["Do you think it's likely that {0} ?",
            "Do you wish that {0} ?",
            "What do you know about {0} ?",
            "Really, if {0} ?",
            "What would you do if {0} ?",
            "But what are the chances that {0} ?",
            "What does this speculation lead to ?"]],

            [r'\sdreamed|\sdream(\w+.*)',
            ["Really, {0} ?",
            "Have you ever fantasized {0} while you were awake ?",
            "Have you ever dreamed {0} before ?",
            "What does that dream suggest to you ?",
            "Do you dream often ?",
            "What persons appear in your dreams ?",
            "Do you believe that dreams have something to do with your problem ?"]],

            [r'\sperhaps\s',
            ["You don't seem quite certain.",
            "Why the uncertain tone ?",
            "Can't you be more positive ?",
            "You aren't sure ?",
            "Don't you know ?",
            "How likely, would you estimate ?"]],

            [r'\sname\s',
            ["I am not interested in names.",
            "OK, my name is bweezy. What do you need to know ?",
            "I've told you before, I don't care about names -- please continue."]],

            [r'(\shello\s|\shi\s|\shey\s)',
            ["How do you do.  Please state your problem.",
            "Hi.  What seems to be your problem ?"]],

            [r'\scomputer\s',
            ["Do computers worry you ?",
            "Why do you mention computers ?",
            "What do you think computers have to do with your problem ?",
            "Don't you think computers can help people ?",
            "What about computers worries you ?",
            "What do you think about computers ?",
            "You don't think I am a computer bot, do you ?"]],

            [r'\sam i (\w+.*)',
            ["Do you believe you are {0} ?",
            "Would you want to be {0} ?",
            "Do you wish I would tell you you are {0} ?",
            "What would it mean if you were {0} ?"]],

            [r'\sare you(\w+.*)',
            ["Why are you interested in whether I am {1} or not ?",
            "Would you prefer if I weren't {1} ?",
            "Perhaps I am {1} in your fantasies.",
            "Do you sometimes think I am {1} ?",
            "Would it matter to you ?",
            "What if I were {1} ?"]],

            [r'\sare (\w+.*)',
            ["Did you think they might not be {1} ?",
            "Would you like it if they were not {1} ?",
            "What if they were not {1} ?",
            "Are they always {1} ?",
            "Possibly they are {1}.",
            "Are you positive they are {1} ?"]],

            [r'(.*)\syour(.*)',
            ["Why are you concerned over my {1} ?",
            "What about your own {1} ?",
            "Are you worried about someone else's {1} ?",
            "Really, my {1} ?",
            "What makes you think of my {1} ?",
            "Do you want my {1} ?"]],

            [r'(.*)\swas i (.*)',
            ["What if you were {1} ?",
            "Do you think you were {1} ?",
            "Were you {1} ?",
            "What would it mean if you were {1} ?",
            "What does ' {1} ' suggest to you ?",
            "goto what"]],

            [r'(.*) i was (.*)',
            ["Were you really ?",
            "Why do you tell me you were {1} now ?",
            "Perhaps I already know you were {1}."]],

            [r'(.*) was you(.*)',
            ["Would you like to believe I was {1} ?",
            "What suggests that I was {1} ?",
            "What do you think ?",
            "Perhaps I was {1}.",
            "What if I had been {1} ?"]],

            [r'(.*) desire(.*)',
            ["What would it mean to you if you got {1} ?",
            "Why do you want {1} ?",
            "Suppose you got {1} soon.",
            "What if you never got {1} ?",
            "What would getting {1} mean to you ?",
            "What does wanting {1} have to do with this discussion ?"]],

            [r'(.*)i am (.*) sad(.*)',
            ["I am sorry to hear that.",
            "Do you think coming here will help you not to be sad ?",
            "I'm sure it's not pleasant to be sad.",
            "Can you explain what made you sad?"]],

            [r'(.*)i am (.*) happy(.*)',
            ["How have I helped you to be happy ?",
            "Has your treatment made you happy ?",
            "What makes you happy just now ?",
            "Can you explain why you are suddenly happy ?"]],

            [r'(.*)i (.*) belive(.*)',
            ["Do you really think so ?",
            "But you are not sure you {2}.",
            "Do you really doubt you {2} ?"]],

            [r'(.*)i am (.*)',
            ["Is it because you are {1} that you came to me ?",
            "How long have you been {1} ?",
            "Do you believe it is normal to be {1} ?",
            "Do you enjoy being {1} ?",
            "Do you know anyone else who is {1} ?",
            "Are you {1} because of your family ?",
            "Are you {1} because of your frinds ?",
            "Are your friends {1} too ?"]],

            [r'(.*)i cannot|i can\'t(.*)',
            ["How do you know that you can't {1} ?",
            "Have you tried ?",
            "Perhaps you could {1} now.",
            "Do you really want to be able to {1} ?",
            "What if you could {1} ?"]],

            [r'(.*)i don\'t(.*)',
            ["Don't you really {1} ?",
            "Why don't you {1} ?",
            "Do you wish to be able to {1} ?",
            "Does that trouble you ?"]],

            [r'(.*)i feel(.*)',
            ["Tell me more about such feelings.",
            "Do you often feel {1} ?",
            "Do you enjoy feeling {1} ?",
            "Of what does feeling {1} remind you ?"]],

            [r'(.*)i (.*) you(.*)',
            ["Perhaps in your fantasies we {1} each other.",
            "Do you wish to {1} me ?",
            "You seem to need to {1} me.",
            "Do you {1} anyone else ?"]],

            [r'(.*)you are |you\'re (.*)',
            ["What makes you think I am {1} ?",
            "Does it please you to believe I am {1} ?",
            "Do you sometimes wish you were {1} ?",
            "Perhaps you would like to be {1}."]],

            [r'(.*)you (.*) me(.*)',
            ["Why do you think I {1} you ?",
            "You like to think I {1} you -- don't you ?",
            "What makes you think I {1} you ?",
            "Really, I {1} you ?",
            "Do you wish to believe I {1} you ?",
            "Suppose I did {1} you -- what would that mean ?",
            "Does someone else believe I {1} you ?"]],

            [r'(.*)you (.*)',
            ["We were discussing you -- not me.",
            "Oh, I {1} ?",
            "You're not really talking about me -- are you ?",
            "What are your feelings now ?"]],

            [r'\syes\s(.*)',
            ["You seem to be quite positive.",
            "You are sure.",
            "I see.",
            "I understand."]],

            [r'\smy (.*)',
            ["Does that have anything to do with the fact that your {0} ?",
            "Lets discuss further why your {0}.",
            "Earlier you said your {0}.",
            "But your {0}."
            "Your {0} ?",
            "Why do you say your {0} ?",
            "Do you like your {0} ",
            "Do you have more than 1 {0} ?",
            "Does that suggest anything else which belongs to you ?",
            "Is it important to you that you have your {0} ?"]],

            [r'\sfamily\s(.*)',
            ["Tell me more about your family.",
            "Who else in your family ?",
            "Your family {0} ?",
            "What else comes to your mind when you think of your family's {0} ?"]],

            [r'\scan you\s(.*)',
            ["You believe I can {0} don't you ?",
            "goto what",
            "You want me to be able to {0}.",
            "Perhaps you would like to be able to {0} yourself."]],

            [r'\scan i\s(.*)',
            ["Whether or not you can {0} depends on you more than on me.",
            "Do you want to be able to {0} ?",
            "Perhaps you don't want to {0}."]],

            [r'(.*)why don\'t you (.*)',
            ["Do you believe I don't {1} ?",
            "Perhaps I will {1} in good time.",
            "Should you {1} yourself ?",
            "You want me to {1} ?"]],

            [r'(.*)why can\'t i (.*)',
            ["Do you think you should be able to {1} ?",
            "Do you want to be able to {1} ?",
            "Do you believe this will help you to {1} ?",
            "Have you any idea why you can't {1} ?"]],

            [r'(.*)because(.*)',
            ["Is that the real reason ?",
            "Don't any other reasons come to mind ?",
            "Does that reason seem to explain anything else ?",
            "What other reasons might there be ?"]],

            [r'(.*)always (.*)',
            ["Can you think of a specific example ?",
            "When ?",
            "What incident are you thinking of ?",
            "Really, always ?"]],

            [r'(.*)alike\s|like\s(.*)',
            ["In what way ?",
            "What resemblence do you see ?",
            "What does that similarity suggest to you ?",
            "What other connections do you see ?",
            "What do you suppose that resemblence means ?",
            "What is the connection, do you suppose ?",
            "Could there really be some connection ?",
            "How ?"]],

            [r'(.*)different\s(.*)',
            ["How is it different ?",
            "What differences do you see ?",
            "What does that difference suggest to you ?",
            "What other distinctions do you see ?",
            "What do you suppose that disparity means ?",
            "Could there be some connection, do you suppose ?",
            "How ?"]],

            [r'(\swhat\s|\swho\s|\swhen\s|\swhy\s|\swhere\s|\show\s)(.*)',
            ["Why do you ask ?",
            "Does that question interest you ?",
            "What is it you really want to know ?",
            "Are such questions much on your mind ?",
            "What answer would please you most ?",
            "What do you think ?",
            "What comes to mind when you ask that ?",
            "Have you asked such questions before ?",
            "Have you asked anyone else ?"]],

            [r'(\snobody\s|\snoone\s|\sno one\s)(.*)',
            ["Are you sure, no one {0} ?",
            "Surely someone {0} .",
            "Can you think of anyone at all ?",
            "Are you thinking of a very special person ?",
            "Who, may I ask ?",
            "You have a particular person in mind, don't you ?",
            "Who do you think you are talking about ?"]],

            [r'(\severyone\s|\severybody\s)(.*)',
            ["Really, everyone ?",
            "Surely not everybody.",
            "Can you think of anyone in particular ?",
            "Who, for example?",
            "Are you thinking of a very special person ?",
            "Who, may I ask ?",
            "Someone special perhaps ?",
            "You have a particular person in mind, don't you ?",
            "Who do you think you're talking about ?"]],
            
            [r'\sno\s',
            ["Are you saying no just to be negative?",
            "You are being a bit negative.",
            "Why not ?",
            "Why 'no' ?"]],

            [r'(.*)',
            ["You say {0} ?",
            "Can you elaborate on that ?",
            "Do you say {0} for some special reason ?",
            "{0}. Really?",
            "When did you first think about {0}",
            "I'm not sure I understand you fully.",
            "Please go on.",
            "Can you repeat that please ?",
            "What does that suggest to you ?",
            "Do you feel strongly about discussing such things ?",
            "That is interesting.  Please continue.",
            "Tell me more about that.",
            "Do go on.",
            "Please talk more about it",
            "Does talking about this bother you ?",
            "Can you rephrase that ?",
            "I see. Tell me more.",
            "Interesting. Is this something you are sorry about ?",
            "Mmm hmmm. Is this is your favorite subject ?",
            "Now we are getting somewhere. Explain more.",
            "I see. How does that make you feel ?"]]
            ]

