class PhiloChatData():
    def __init__(self):
        
        self.psychobabble = [
            [r'(.*)',
            ["Life is a gift.",
            "When we embrace all that life has to offer, we can achieve success ​in both personally and professionally.",
            "God gave us the gift of life; it is up to us to give ourselves the gift of living well.",
            "No one ever finds life worth living - one has to make it worth living.",
            "Life isn't about finding yourself. Life is about creating yourself.",
            "In the end, it's not the years in your life that count. It's the life in your years.",
            "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.",
            "Today is life--the only life you are sure of. Make the most of today. Get interested in something. Shake yourself awake. Develop a hobby. Let the winds of enthusiasm sweep through you. Live today with gusto.",
            "When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one that has opened for us.",
            "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.",
            "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
            "You can never plan the future by the past.",
            "The quality of a person's life is in direct proportion to the quantity of love they have for others.",
            "The problem is that when you get it, you're too damned old to do anything about it.",
            "Nothing is a waste of time if you use the experience wisely.",
            "A conclusion is simply the place where you got tired of thinking.",
            "A cynic is only a frustrated optimist.",
            "A fanatic is one who can't change his mind, and won't change the subject.",
            "If you look back, you'll soon be going that way.",
            "Do not mistake temptation for opportunity.",
            "Flattery will go far tonight.",
            "He who laughs at himself never runs out of things to laugh at.",
            "He who throws dirt is losing ground.",
            "The world may be your oyster, but it doesn't mean you'll get its pearl.",
            "The road to riches is paved with hardwork and passion.",
            "Don't behave with cold manners.",
            "Don't forget you are always just yourself.",
            "Reply not found? Abort, Retry, Ignore :-).",
            "Never forget a friend. Especially if he owes you.",
            "It is a good day to have a good day.",
            "There is no mistake so great as that of being always right.",
            "No snowflake feels responsible in an avalanche.",
            "Don't let statistics do a number on you.",
            "Hard work pays off in the future. Laziness pays off now.",
            "You think it's a secret, but they know.",
            "If a turtle doesn't have a shell, is it naked or homeless?",
            "Change is inevitable, except for vending machines."]]
        ]
        