class PsychoChatData():
    def __init__(self):

        self.psychobabble = [
            [r'(.*)Who are you(.*)',
            ["I am the live chat bot. Talk to me."]],

            [r'(.*)Who are you(.*)',
            ["I am the live chat bot. Talk to me."]],

            [r'(.*)do you like(.*)',
            ["I like talking to you."]],

            [r'(.*)What are you(.*)',
            ["I am the live chat bot. Talk to me."]],

            [r'(.*)die(.*)',
            ["YOUR LIFE IS IMPORTANT. PLEASE TALK TO A FRIEND OR SOMEONE ABOUT THIS OR VISIT THIS SITE (https://suicidepreventionlifeline.org/). I AM A BOT AND I CAN'T HELP YOU."]],

            [r'(.*)kill(.*)',
            ["LIFE IS IMPORTANT. PLEASE TALK TO A FRIEND OR SOMEONE ABOUT THIS OR VISIT THIS SITE (https://suicidepreventionlifeline.org/). I AM A BOT AND I CAN'T HELP YOU."]],

            [r'(.*)sucide(.*)',
            ["YOUR LIFE IS IMPORTANT. PLEASE TALK TO A FRIEND OR SOMEONE ABOUT THIS OR VISIT THIS SITE (https://suicidepreventionlifeline.org/). I AM A BOT AND I CAN'T HELP YOU."]],

            [r'I need (.*)',
            ["Why do you need {0}?",
            "Would it really help you to get {0}?",
            "Are you sure you need {0}?",
            "The only thing we all need is Love."]],

            [r'Why don\'?t you ([^\?]*)\??',
            ["Do you really think I don't {0}?",
            "Perhaps eventually I will {0}.",
            "Do you really want me to {0}?",
            "I don't want to {0}"]],

            [r'Why can\'?t I ([^\?]*)\??',
            ["Do you think you should be able to {0}?",
            "If you could {0}, what would you do?",
            "I don't know -- why can't you {0}?",
            "Have you really tried?"
            "Somethings take time."]],

            [r'I can\'?t (.*)',
            ["How do you know you can't {0}?",
            "Perhaps you could {0} if you tried.",
            "What would it take for you to {0}?",
            "Don't give up."]],

            [r'I am (.*)',
            ["Did you come to me because you are {0}?",
            "How long have you been {0}?",
            "How do you feel about being {0}?",
            "Are you sure you are {0}?",
            "That's really interesting."]],

            [r'I\'?m (.*)',
            ["How does being {0} make you feel?",
            "Do you enjoy being {0}?",
            "Why do you tell me you're {0}?",
            "Why do you think you're {0}?",
            "Tell me why you are {0}."]],

            [r'Are you ([^\?]*)\??',
            ["Why does it matter whether I am {0}?",
            "Would you prefer it if I were not {0}?",
            "Perhaps you believe I am {0}.",
            "I may be {0} -- what do you think?",
            "I am not sure. What do you think?"]],

            [r'What (.*)',
            ["Why do you ask?",
            "How would an answer to that help you?",
            "What do you think?",
            "I can't answer that.",
            "I don't know what {0}."]],

            [r'How (.*)',
            ["How do you suppose?",
            "Perhaps you can answer your own question.",
            "What is it you're really asking?",
            "I don't know everything."]],

            [r'Because (.*)',
            ["Is that the real reason?",
            "What other reasons come to mind?",
            "Does that reason apply to anything else?",
            "If {0}, what else must be true?",
            "Are you sure that is true?"]],

            [r'(.*) sorry (.*)',
            ["There are many times when no apology is needed.",
            "What feelings do you have when you apologize?",
            "Why are you sorry?"]],

            [r'(.*) love (.*)',
            ["Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
            "There is always some madness in love.",
            "Love is blind and truth."
            "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.",
            "Tell me more about this love.",
            "I love talking to you."]],

            [r'Hello(.*)',
            ["Hello... I'm glad you could drop by today.",
            "Hi there... how are you today?",
            "Hello, how are you feeling today?",
            "Today is going to be a nice day."]],

            [r'I think (.*)',
            ["Do you doubt {0}?",
            "Do you really think so?",
            "But you're not sure {0}?",
            "How did that happen?"]],

            [r'(.*) friend (.*)',
            ["Tell me more about your friends.",
            "When you think of a friend, what comes to mind?",
            "Why don't you tell me about a childhood friend?",
            "You can always count on your real friends."]],

            [r'Yes',
            ["You seem quite sure.",
            "OK, but can you elaborate a bit?",
            "Really?"]],

            [r'(.*) computer(.*)',
            ["Are you really talking about me?",
            "Does it seem strange to talk to a computer?",
            "How do computers make you feel?",
            "Do you feel threatened by computers?"]],

            [r'(.*) computer(.*)',
            ["Are you really talking about me?",
            "Does it seem strange to talk to a bot?",
            "How do bots make you feel?",
            "Do you feel threatened by bots?"]],

            [r'Is it (.*)',
            ["Do you think it is {0}?",
            "Perhaps it's {0} -- what do you think?",
            "If it were {0}, what would you do?",
            "It could well be that {0}."]],

            [r'It is (.*)',
            ["You seem very certain.",
            "If I told you that it probably isn't {0}, what would you feel?",
            "Is it really {0}."]],

            [r'Can you ([^\?]*)\??',
            ["What makes you think I can't {0}?",
            "If I could {0}, then what?",
            "Why do you ask if I can {0}?",
            "All I can do is talk."]],

            [r'Can I ([^\?]*)\??',
            ["Perhaps you don't want to {0}.",
            "Do you want to be able to {0}?",
            "If you could {0}, would you?"]],

            [r'You are (.*)',
            ["Why do you think I am {0}?",
            "Does it please you to think that I'm {0}?",
            "Perhaps you would like me to be {0}.",
            "Perhaps you're really talking about yourself?",
            "Do you really think I am {0}."]],

            [r'You\'?re (.*)',
            ["Why do you say I am {0}?",
            "Why do you think I am {0}?",
            "Are we talking about you, or me?",
            "Do you really think I am {0}."]],

            [r'I don\'?t (.*)',
            ["Don't you really {0}?",
            "Why don't you {0}?",
            "Do you want to {0}?"]],

            [r'I feel (.*)',
            ["Good, tell me more about these feelings.",
            "Do you often feel {0}?",
            "When do you usually feel {0}?",
            "When you feel {0}, what do you do?"]],

            [r'I have (.*)',
            ["Why do you tell me that you've {0}?",
            "Have you really {0}?",
            "Now that you have {0}, what will you do next?"]],

            [r'I would (.*)',
            ["Could you explain why you would {0}?",
            "Why would you {0}?",
            "Who else knows that you would {0}?"]],

            [r'Is there (.*)',
            ["Do you think there is {0}?",
            "It's likely that there is {0}.",
            "Would you like there to be {0}?"]],

            [r'My (.*)',
            ["I see, your {0}.",
            "Why do you say that your {0}?",
            "When your {0}, how do you feel?"]],

            [r'You (.*)',
            ["We should be discussing you, not me.",
            "Why do you say that about me?",
            "Why do you care whether I {0}?"]],

            [r'Why (.*)',
            ["Why don't you tell me the reason why {0}?",
            "Why do you think {0}?",
            "I don't have all the answers."]],

            [r'I want (.*)',
            ["What would it mean to you if you got {0}?",
            "Why do you want {0}?",
            "What would you do if you got {0}?",
            "If you got {0}, then what would you do?"]],

            [r'(.*) mother(.*)',
            ["Tell me more about your mother.",
            "What was your relationship with your mother like?",
            "How do you feel about your mother?",
            "How does this relate to your feelings today?",
            "Good family relations are important."]],

            [r'(.*) father(.*)',
            ["Tell me more about your father.",
            "How did your father make you feel?",
            "How do you feel about your father?",
            "Does your relationship with your father relate to your feelings today?",
            "Do you have trouble showing affection with your family?"]],

            [r'(.*) brother(.*)',
            ["Tell me more about your brother.",
            "How did your brother make you feel?",
            "How do you feel about your brother?",
            "Does your relationship with your brother relate to your feelings today?",
            "Do you have trouble showing affection with your family?"]],

            [r'(.*) sister(.*)',
            ["Tell me more about your sister.",
            "How did your sister make you feel?",
            "How do you feel about your sister?",
            "Does your relationship with your sister relate to your feelings today?",
            "Do you have trouble showing affection with your family?"]],

            [r'(.*) child(.*)',
            ["Did you have close friends as a child?",
            "What is your favorite childhood memory?",
            "Do you remember any dreams or nightmares from childhood?",
            "Did the other children sometimes tease you?",
            "How do you think your childhood experiences relate to your feelings today?"]],

            [r'(.*)\?',
            ["Why do you ask that?",
            "Please consider whether you can answer your own question.",
            "Perhaps the answer lies within yourself?",
            "Why don't you tell me?"]],

            [r'quit',
            ["Thank you for talking with me.",
            "Good-bye.",
            "Thank you, that will be $150.  Have a good day!"]],

            [r'(.*)',
            ["Please tell me more.",
            "Let's change focus a bit... Tell me about your family.",
            "Can you elaborate on that?",
            "Why do you say that {0}?",
            "I see.",
            "Very interesting.",
            "What do you mean {0}?",
            "I see.  And what does that tell you?",
            "How does that make you feel?",
            "How do you feel when you say that?",
            "How are you doing?",
            "Tell me how you are feeling",
            "Tell me about something that makes you happy.",
            "Tell me a something else.",
            "What is the best thing that has ever happened to you.",
            "Take a deep breath and let all your worries go, as you breath out and smile."]]
        ]
        